// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgTQKcrZ0BFePaBQIHUY00pFcPNC45AcU',
    appId: '1:179254832097:web:f9d1b0d5b1e483fffa40a0',
    messagingSenderId: '179254832097',
    projectId: 'pandai-app-a98b6',
    authDomain: 'pandai-app-a98b6.firebaseapp.com',
    storageBucket: 'pandai-app-a98b6.firebasestorage.app',
    measurementId: 'G-FB3K72TCCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrsphd7NVTlfEXnZb70myR9ymA7rJFimU',
    appId: '1:179254832097:android:515e6d02b9daa350fa40a0',
    messagingSenderId: '179254832097',
    projectId: 'pandai-app-a98b6',
    storageBucket: 'pandai-app-a98b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE9KKseSJKq0iN0hhgKY4ZgnaTUQBag58',
    appId: '1:179254832097:ios:235d8e8526a05524fa40a0',
    messagingSenderId: '179254832097',
    projectId: 'pandai-app-a98b6',
    storageBucket: 'pandai-app-a98b6.firebasestorage.app',
    iosBundleId: 'com.example.pandaiapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE9KKseSJKq0iN0hhgKY4ZgnaTUQBag58',
    appId: '1:179254832097:ios:235d8e8526a05524fa40a0',
    messagingSenderId: '179254832097',
    projectId: 'pandai-app-a98b6',
    storageBucket: 'pandai-app-a98b6.firebasestorage.app',
    iosBundleId: 'com.example.pandaiapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgTQKcrZ0BFePaBQIHUY00pFcPNC45AcU',
    appId: '1:179254832097:web:6ba3905eea437258fa40a0',
    messagingSenderId: '179254832097',
    projectId: 'pandai-app-a98b6',
    authDomain: 'pandai-app-a98b6.firebaseapp.com',
    storageBucket: 'pandai-app-a98b6.firebasestorage.app',
    measurementId: 'G-MVZJP01LCW',
  );
}
